### ISSUE TITLE
Crash node.js

### ISSUE THREAD

**Issue by xyrox54** [muscleman/progpowz-nodejs-pool#2]
Hi !

I have this problem when launching node.js and I can't find where the problem comes from.
An idea ?

```
/home/pool/pool/lib/utils.js:27
let addressBase58Prefix = parseInt(cnUtil.address_decode(Buffer.from(config.poolServer.poolAddress)).toString());
                                                                                                    ^

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/home/pool/pool/lib/utils.js:27:101)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pool/pool/lib/daemon.js:45:13)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
2022-01-23 11:19:18 [master] Daemon died, spawning replacement...

```

**Comment by muscleman** [comment]
think the error basically tells you the issue. take another look at your config.json file
